databases:
  - name: suscamdb
    plan: free
    databaseName: suscam
    user: suscam

services:
  - type: web
    plan: free
    name: suscam
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn suscam.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: suscamdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
