databases:
  - name: sustainableCampusdb
    plan: free
    databaseName: sustainableCampus
    user: sustainableCampus

services:
  - type: web
    plan: free
    name: sustainableCampus
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn sustainableCampus.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sustainableCampusdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
