# Generated by Django 5.1.6 on 2025-03-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dailyQuiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
