# Generated by Django 5.1.6 on 2025-03-22 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_type', models.IntegerField()),
                ('rarity', models.IntegerField()),
                ('plant_name', models.TextField(default='plant')),
            ],
        ),
        migrations.CreateModel(
            name='UserForest',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cells', models.TextField(default='{cell_0 : [0,0,0], cell_1 : [0,0,0], cell_2 : [0,0,0], cell_3 : [0,0,0], cell_4 : [0,0,0], cell_5 : [0,0,0], cell_6 : [0,0,0], cell_7 : [0,0,0], cell_8 : [0,0,0], cell_9 : [0,0,0], cell_10 : [0,0,0], cell_11 : [0,0,0], cell_12 : [0,0,0], cell_13 : [0,0,0], cell_14 : [0,0,0],cell_15 : [0,0,0]}', max_length=2048)),
                ('last_growth_check_date', models.TextField(default="<class 'datetime.date'>")),
            ],
        ),
        migrations.CreateModel(
            name='UserInventory',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('paper', models.IntegerField(default=0)),
                ('plastic', models.IntegerField(default=0)),
                ('compost', models.IntegerField(default=0)),
                ('recycled_paper', models.IntegerField(default=0)),
                ('recycled_plastic', models.IntegerField(default=0)),
                ('recycled_compost', models.IntegerField(default=0)),
                ('tree_guard', models.IntegerField(default=0)),
                ('rain_catcher', models.IntegerField(default=0)),
                ('fertilizer', models.IntegerField(default=0)),
                ('oak', models.IntegerField(default=0)),
                ('birch', models.IntegerField(default=0)),
                ('fir', models.IntegerField(default=0)),
                ('red_campion', models.IntegerField(default=0)),
                ('poppy', models.IntegerField(default=0)),
                ('cotoneaster', models.IntegerField(default=0)),
                ('collected_markers', models.TextField(default='')),
                ('last_collected', models.TextField(default="<class 'datetime.date'>")),
            ],
        ),
    ]
