# Generated by Django 5.1.5 on 2025-03-16 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_customuser_creationdatetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requirement_type", models.IntegerField()),
                ("rarity", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserForest",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserInventory",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("paper", models.IntegerField(default=0)),
                ("plastic", models.IntegerField(default=0)),
                ("compost", models.IntegerField(default=0)),
                ("recycled_paper", models.IntegerField(default=0)),
                ("recycled_plastic", models.IntegerField(default=0)),
                ("recycled_compost", models.IntegerField(default=0)),
                ("tree_guard", models.IntegerField(default=0)),
                ("rain_catcher", models.IntegerField(default=0)),
                ("fertilizer", models.IntegerField(default=0)),
                ("oak", models.IntegerField(default=0)),
                ("birch", models.IntegerField(default=0)),
                ("fir", models.IntegerField(default=0)),
                ("red_campion", models.IntegerField(default=0)),
                ("poppy", models.IntegerField(default=0)),
                ("cotoneaster", models.IntegerField(default=0)),
            ],
        ),
    ]
