# Generated by Django 5.1.5 on 2025-03-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plant",
            name="plant_name",
            field=models.TextField(default="plant"),
        ),
    ]
