# Generated by Django 5.1.6 on 2025-03-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinventory',
            name='last_collected',
            field=models.TextField(default="<class 'datetime.date'>"),
        ),
    ]
