# Generated by Django 5.1.5 on 2025-03-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_plant_plant_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="userforest",
            name="cells",
            field=models.TextField(default="", max_length=2048),
        ),
    ]
