# Generated by Django 5.1.6 on 2025-03-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userinventory_last_collected'),
    ]

    operations = [
        migrations.AddField(
            model_name='userforest',
            name='last_growth_check_date',
            field=models.TextField(default="<class 'datetime.date'>"),
        ),
    ]
