# Generated by Django 5.1.5 on 2025-03-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_userforest_cells"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userforest",
            name="cells",
            field=models.TextField(
                default="{cell_0 : [0,0,0], cell_1 : [0,0,0], cell_2 : [0,0,0], cell_3 : [0,0,0], cell_4 : [0,0,0], cell_5 : [0,0,0], cell_6 : [0,0,0], cell_7 : [0,0,0], cell_8 : [0,0,0], cell_9 : [0,0,0], cell_10 : [0,0,0], cell_11 : [0,0,0], cell_12 : [0,0,0], cell_13 : [0,0,0], cell_14 : [0,0,0],cell_15 : [0,0,0]}",
                max_length=2048,
            ),
        ),
    ]
