# Generated by Django 5.1.5 on 2025-03-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_userforest_cells"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinventory",
            name="collected_markers",
            field=models.TextField(default=""),
        ),
    ]
