# Generated by Django 5.1.5 on 2025-03-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_userinventory_collected_markers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinventory",
            name="collected_markers",
            field=models.TextField(default="{}"),
        ),
    ]
