# Generated by Django 5.1.6 on 2025-03-02 21:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_announcement_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_event',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='summary',
            field=models.TextField(max_length=200),
        ),
        migrations.CreateModel(
            name='EventReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_reward', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(300)])),
                ('transaction_description', models.TextField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_code', models.TextField(max_length=32)),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='announcements.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttended',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.eventreward')),
            ],
        ),
    ]
