# Generated by Django 5.1.6 on 2025-03-05 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcement_is_event_alter_announcement_summary_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventReward',
            new_name='Event',
        ),
    ]
