# Generated by Django 5.1.5 on 2025-03-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0004_alter_announcement_summary"),
        ("announcements", "0005_rename_eventreward_event"),
    ]

    operations = []
